pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
      stage('Build') {
            steps {
                // Checkout the source code from your version control system (e.g., Git)
                // Adjust the URL and credentials as needed
                git 'https://github.com/anilyadav3317/Mini-project-1.git'

                // Run 'mvn clean install' to build the Java application
                sh 'mvn clean install'
            }
        }
               
    }
}

